
spring:
  application:
    name: stockapp-eurekaserver
  #config:
    #import: ${EXT_CONFIG_URL}
# url agregado como propiedad en Run As: Run Configurations... como si fuera una propiedad establecida al inicio